# Generated by Django 5.2.6 on 2025-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(),
        ),
    ]
